SET SESSION sql_mode = '';

DROP TABLE IF EXISTS ADD_TIME;
DROP TABLE IF EXISTS accounting_errors;
DROP TABLE IF EXISTS remote_work;
DROP TABLE IF EXISTS visiting;
DROP TABLE IF EXISTS Delays;
DROP TABLE IF EXISTS DBSETUP;
DROP TABLE IF EXISTS work_dayoff;
DROP TABLE IF EXISTS staff_leaves;
DROP TABLE IF EXISTS `GROUPS`;
DROP TABLE IF EXISTS auth_remember_tokens;
DROP TABLE IF EXISTS business_trip_missing_data;
DROP TABLE IF EXISTS employees;

CREATE TABLE employees (
    ID INT NOT NULL PRIMARY KEY,
    LOGIN VARCHAR(100) NOT NULL DEFAULT '',
    PASSWD CHAR(32) NOT NULL DEFAULT '',
    FIRSTNAME VARCHAR(100) NOT NULL DEFAULT '',
    LASTNAME VARCHAR(100) NOT NULL DEFAULT '',
    SURNAME VARCHAR(100) NOT NULL DEFAULT '',
    PHONE VARCHAR(100) NOT NULL DEFAULT '',
    PERSONAL_PHONE VARCHAR(100) NOT NULL DEFAULT '',
    CORPORATE_PHONE VARCHAR(100) NOT NULL DEFAULT '',
    BIRTHDAY DATE NULL,
    EMAIL VARCHAR(255) NOT NULL DEFAULT '',
    RELEVANCE TINYINT NOT NULL DEFAULT 1,
    RemoteWork TINYINT NOT NULL DEFAULT 0,
    rate INT NOT NULL DEFAULT -1,
    defaultStartTime TIME NOT NULL DEFAULT '09:00:00',
    allowedDelayMinutes INT NOT NULL DEFAULT 30,
    userTimeZoneMins INT NOT NULL DEFAULT 0,
    dayTransitionTime TIME NOT NULL DEFAULT '06:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `GROUPS` (
    USERID INT NOT NULL,
    SUPERVISORID INT NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    INDEX groups_user_type (USERID, TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE auth_remember_tokens (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERID INT NOT NULL,
    TOKEN_HASH CHAR(64) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    CREATED_DT DATETIME NOT NULL,
    LAST_USED_DT DATETIME NOT NULL,
    UNIQUE KEY auth_remember_token_hash (TOKEN_HASH),
    KEY auth_remember_user_expires (USERID, EXPIRES_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE business_trip_missing_data (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERID INT NOT NULL,
    TRIP_DATE DATE NOT NULL,
    CREATED_DT DATETIME NOT NULL,
    UNIQUE KEY business_trip_missing_data_user_date (USERID, TRIP_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE accounting_errors (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERID INT NOT NULL,
    ERROR_DATE DATE NOT NULL,
    STATUS TINYINT NOT NULL DEFAULT 0,
    COMMENT TEXT NOT NULL,
    CREATED_DT DATETIME NOT NULL,
    UNIQUE KEY accounting_errors_user_date (USERID, ERROR_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE visiting (
    ID INT NOT NULL PRIMARY KEY,
    user_id INT NOT NULL,
    in_dt DATETIME NOT NULL,
    eat_start_dt DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    eat_stop_dt DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    out_dt DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    state TINYINT NOT NULL DEFAULT 1,
    remoteWorkState TINYINT NOT NULL DEFAULT 0,
    dayTransitionTime TIME NOT NULL DEFAULT '06:00:00',
    take_pause TINYINT NOT NULL DEFAULT 0,
    INDEX visiting_user_in (user_id, in_dt, ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ADD_TIME (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ADDDATE DATE NOT NULL,
    SUIR INT NOT NULL,
    USERID INT NOT NULL,
    START_DT DATETIME NOT NULL,
    STOP_DT DATETIME NULL,
    REASON INT NOT NULL DEFAULT -1,
    DESCRIPTION TEXT NOT NULL,
    SUPERVISORDESC TEXT NOT NULL,
    APPROVED TINYINT NOT NULL DEFAULT 0,
    PAUSE_MODE TINYINT NOT NULL DEFAULT 0,
    BYALERT TINYINT NOT NULL DEFAULT 0,
    INDEX add_time_user_start (USERID, START_DT, ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Delays (
    ID INT NOT NULL PRIMARY KEY,
    date DATE NOT NULL,
    duration VARCHAR(32) NOT NULL,
    userID INT NOT NULL,
    supervisorID INT NOT NULL DEFAULT -1,
    explaneDesk TEXT NOT NULL,
    acceptorID INT NOT NULL DEFAULT -1,
    penaltyID INT NOT NULL DEFAULT -1,
    penaltyReply TEXT NOT NULL,
    status INT NOT NULL DEFAULT 0,
    INDEX delays_user_date (userID, date, ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE DBSETUP (
    paramName VARCHAR(100) NOT NULL PRIMARY KEY,
    valueInt INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE work_dayoff (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    type INT NOT NULL DEFAULT 0,
    UNIQUE KEY work_dayoff_date (date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE staff_leaves (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    fio VARCHAR(255) NOT NULL DEFAULT '',
    start_date DATE NOT NULL,
    stop_date DATE NOT NULL,
    event VARCHAR(100) NOT NULL,
    INDEX staff_leaves_user_dates (user_id, start_date, stop_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE remote_work (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    supervisor_id INT NOT NULL,
    start_dt DATETIME NOT NULL,
    stop_dt DATETIME NULL,
    INDEX remote_work_user_start (user_id, start_dt, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
