SET SESSION sql_mode = '';

DROP TABLE IF EXISTS ADD_TIME;
DROP TABLE IF EXISTS remote_work;
DROP TABLE IF EXISTS visiting;
DROP TABLE IF EXISTS `GROUPS`;
DROP TABLE IF EXISTS employees;

CREATE TABLE employees (
    ID INT NOT NULL PRIMARY KEY,
    FIRSTNAME VARCHAR(100) NOT NULL DEFAULT '',
    LASTNAME VARCHAR(100) NOT NULL DEFAULT '',
    SURNAME VARCHAR(100) NOT NULL DEFAULT '',
    PHONE VARCHAR(100) NOT NULL DEFAULT '',
    PERSONAL_PHONE VARCHAR(100) NOT NULL DEFAULT '',
    CORPORATE_PHONE VARCHAR(100) NOT NULL DEFAULT '',
    BIRTHDAY DATE NULL,
    EMAIL VARCHAR(255) NOT NULL DEFAULT '',
    RELEVANCE TINYINT NOT NULL DEFAULT 1,
    RemoteWork TINYINT NOT NULL DEFAULT 0,
    dayTransitionTime TIME NOT NULL DEFAULT '06:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `GROUPS` (
    USERID INT NOT NULL,
    SUPERVISORID INT NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    INDEX groups_user_type (USERID, TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE visiting (
    ID INT NOT NULL PRIMARY KEY,
    user_id INT NOT NULL,
    in_dt DATETIME NOT NULL,
    eat_start_dt DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    eat_stop_dt DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    out_dt DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    state TINYINT NOT NULL DEFAULT 1,
    remoteWorkState TINYINT NOT NULL DEFAULT 0,
    dayTransitionTime TIME NOT NULL DEFAULT '06:00:00',
    take_pause TINYINT NOT NULL DEFAULT 0,
    INDEX visiting_user_in (user_id, in_dt, ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ADD_TIME (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ADDDATE DATE NOT NULL,
    SUIR INT NOT NULL,
    USERID INT NOT NULL,
    START_DT DATETIME NOT NULL,
    STOP_DT DATETIME NULL,
    REASON INT NOT NULL DEFAULT -1,
    DESCRIPTION TEXT NOT NULL,
    SUPERVISORDESC TEXT NOT NULL,
    APPROVED TINYINT NOT NULL DEFAULT 0,
    PAUSE_MODE TINYINT NOT NULL DEFAULT 0,
    BYALERT TINYINT NOT NULL DEFAULT 0,
    INDEX add_time_user_start (USERID, START_DT, ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE remote_work (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    supervisor_id INT NOT NULL,
    start_dt DATETIME NOT NULL,
    stop_dt DATETIME NULL,
    INDEX remote_work_user_start (user_id, start_dt, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
