CREATE TABLE IF NOT EXISTS accounting_errors (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    USERID INT NOT NULL,
    ERROR_DATE DATE NOT NULL,
    STATUS TINYINT NOT NULL DEFAULT 0,
    USER_COMMENT TEXT NULL,
    SUPERVISORID INT NULL,
    SUPERVISOR_COMMENT TEXT NULL,
    CREATED_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_REPLY_DT DATETIME NULL,
    SUPERVISOR_REPLY_DT DATETIME NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_accounting_errors_user_date (USERID, ERROR_DATE),
    KEY idx_accounting_errors_status_date (STATUS, ERROR_DATE),
    KEY idx_accounting_errors_supervisor (SUPERVISORID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
